### ISSUE TITLE
Presence of Braindate logic

### ISSUE THREAD

**Issue by RosaliePerron** [MaxDude132/drf-serializer-prefetch#9]
Presence of Braindate logic at multiple places in https://github.com/MaxDude132/drf-serializer-prefetch/blob/main/serializer_prefetch/base.py.

**Comment by MaxDude132** [comment]
I see some names have not been properly changed, true. Other than `_braindate_prefetch_done` which should be changed to `_serializer_prefetch_done`, did you find anything else?

**Comment by MaxDude132** [comment]
Note that `_braindate_prefetch_done` had nothing to do with the actual logic, so just changing the name should be enough to be rid of the logic
